### ISSUE TITLE
Export/Create a new homedir API method

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/rc#10]
Export (create) a new API method `homedir`. The goal is to design an API similar to Node.js [os.homedir](https://nodejs.org/api/os.html#oshomedir).

When we need to create and manage a "global" configuration on the system we need a dedicated directory for NodeSecure (to store the configuration).

This new method should return the path to a **nodesecure** directory is the os home directory:
```js
import os from "os";
import path from "path";

// !! This !!
path.join(os.homedir(), "nodesecure")
```

The new API must be used like this:
```js
import * as rc from "@nodesecure/rc";

rc.homedir();
```

This new API will be useful in our tools like CLI or CI (for example, look at `kHomePath` const: https://github.com/NodeSecure/cli/pull/104).

**Comment by PierreDemailly** [comment]
I'm on it
