### ISSUE TITLE
In-memory/memoize payload API

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/rc#14]
I think it might be nice to have an in-memory API for RC. This would simplify implementations on some projects that are spread over several packages.

Example of two new API:
- .memoize()
- .memoized() 

```ts
const configurationPayload = (
    await RC.read(void 0, { createMode: "ci" })
).unwrap();

/**
 * OVERWRITE [TRUE]: Overwrite the previous memoized payload
 * OVERWRITE [FALSE]: Merge with the previous memoized payload
 */
RC.memoize(configurationPayload, { overwrite: false });

const result = RC.memoized({
    default: {}
}).unwrap();
```

Automatically memoize using .read() API:
```ts
const configurationPayload = (
    await RC.read(void 0, { createMode: "ci", memoize: true })
).unwrap();

const result = RC.memoized({
    default: {}
}).unwrap();
```

> **Note**: The default options allow to set a default value if there is no memoized value.

**Comment by fabnguess** [comment]
Hello @fraxken, I would like to discuss this issue that interests me. Could you explain to me how the "memoize" method will work? Will we have an existing object that we can work on or will we have to create a new one in memory for this purpose?

**Comment by fraxken** [comment]
Hello @fabnguess what do you mean by how the "memoize" will work?

The idea is just to keep a runtime configuration in memory (with a new `memoize` API) and then be able to get it with `memoized` API (look at my example).

As my example state we can then add options to:
- Automatically memoize when using **read** API.
- Overwrite (merging or not) using memoize. Look at [lodash.merge](https://www.geeksforgeeks.org/lodash-_-merge-method/).
- Getting a default value when using **memoized** API (if there is no config in memory).

Overall you need to be familiar with those concepts and with the package itself.

**Comment by fraxken** [comment]
Fairly simple example

```js
let memoizedValue = null;

export function memoize(obj) {
  // TODO: validating obj is a valid rc?

  memoizedValue = obj;
}

export function memoized(options = {}) {
  const { defaultValue } = options;

  return memoizedValue === null ? defaultValue : memoizedValue;
}
```
