### ISSUE TITLE
nodesecurerc.json schema is not included in the dist folder generated by TypeScript

### ISSUE THREAD

**Issue by antoine-coulon** [NodeSecure/rc#5]
Hello,

It appears that the `nodesecurerc.json` schema is not included in the dist folder resulting in a runtime error when using the `read` API.

I'm probably going to open a PR to solve this issue, which I think is basically adding the JSON file in the `include` section of the `tsconfig.json`

**Comment by fraxken** [comment]
@all-contributors please add @antoine-coulon for code, bug, review
